swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: '
  <script>
    console.log("Page altered by pipodzarmy.");
  </script>
'
paths:
  /:
    post:
      responses:
        '200':
          description: hacked by pipodz army
